### ISSUE TITLE
Cannot load M3U8

### ISSUE THREAD

**Issue by KiritoPM** [riverlabteam/subanimes-public#23]
Tive esse problema em uma smart TV, pensei que talvez fosse só lá, daí entrei pelo meu celular e teve o mesmo problema.

**Comment by jassriver** [comment]
Bom dia, o erro pode acontecer por queda no servidor de vídeos do site.
Você precisa comunicar à equipe do site através do report de erros nos vídeos no DISCORD do site.

Aqui é pra reportar problemas técnicos referentes ao site.
