### ISSUE TITLE
Nao aparece a verificacao no meu email

### ISSUE THREAD

**Issue by Natgeus** [riverlabteam/subanimes-public#35]
Olá, venho usando o App há dias e resolvi criar uma conta para salvar minhas animações porém quando fui verificar o meu email percebi que não recebi a verificacao mesmo colocando o endereço correto.

**Comment by jassriver** [comment]
O problema no servidor de emails já está sendo corrigido, por hora, pode ignorar a mensagem de aviso de remoção da conta, isso não acontecerá para as pessoas que não receberam o e-mail, não precisa se preocupar :)
