### ISSUE TITLE
Barra de pesquisa/Filtros não está funcionando

### ISSUE THREAD

**Issue by glaucovin** [riverlabteam/subanimes-public#39]
Vi que tinha um report parecido, mas realmente não funciona de maneira alguma, mesmo dando f5 na url que mostraria o resultado da pesquisa, nada acontece... Pesquisar nos filtros também não está dando certo...

**Comment by fffurtado** [comment]
De fato, verificando no console do site, tem um erro na busca:

"Uncaught ReferenceError: js_global is not defined"

**Comment by hirios** [comment]
Me deparei com o mesmo problema e assim como o @fffurtado relatou, parece ser algo com a variável `js_global`

**Comment by jassriver** [comment]
Corrigido.

**Comment by hirios** [comment]
@jassriver o problema persiste
