### ISSUE TITLE
Barra de pesquis/Filtros

### ISSUE THREAD

**Issue by wrldXdrgs** [riverlabteam/subanimes-public#41]
a barra de pesquisa não funciona, quando pesquisado o nome do anime ela fica carregando infinitamente e se clicar na lupa volta para a página inicial do site, com a filtragem de anime quando clico em filtrar só fica carregando e nada acontece vi que esse erro já foi comentado antes e já tá a bastante tempo e continua.

**Comment by jassriver** [comment]
Okay, por favor, não faça flood de issues, bastava comentar em outro issue informando que o problema não foi corrigido, de qualquer maneira, irei fechar esse e averiguar o problema, em breve ele deve ser corrigido e adicionado ao changelog
