### ISSUE TITLE
Problemas com Re: Captcha

### ISSUE THREAD

**Issue by MTangelo** [riverlabteam/subanimes-public#43]
Caros, não consigo logar uma conta ou criar um novo usuario no site do SubAnimes ( http://unpcuz.uk/ ) pois o Captcha não é disponibilizado.
erro : ERRO para o proprietário do site: domínio inválido para a chave do site
![Captcha](https://user-images.githubusercontent.com/98789437/151900503-17497d3b-53a8-43cf-a8ae-bee7100ecd27.PNG)
![Captcha2](https://user-images.githubusercontent.com/98789437/151900664-90075b1d-f6cd-4445-91a5-6f4d99103fab.PNG)
Me ajudem por favor, desde já agradeço. Obrigado !

**Comment by jassriver** [comment]
Sistema de login/cadastro desabilitado momentaneamente para manutenção.
